#Define Linux Environment
dist: bionic
language: bash

branches:
 only:
 - master
before_installation:
 - sudo snap install terraform
jobs:
 include:
 - stage: terraform init
   script:
   - terraform init -force-copy
 - stage: terraform plan
   script:
   - terraform plan
 - stage: terraform apply
   script:
   - terraform apply -auto-approve
 - stage: terraform destroy
   script:
   - terraform destroy -auto-approve
