dist: bionic
language: bash

branches:
 only:
 - master
before_install:
 - wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
 - unzip terraform_0.12.24_linux_amd64.zip
 - sudo mv ./terraform ~/bin
 - terraform --version
terraform_init: &terraform_init
 run:
  name: terraform init
  command: |
   source $BASH_ENV
   cd ~/project/
   terraform init -backend-config="token=${TF_API_TOKEN}"
jobs:
 include:
 - stage: terraform init 
   script:
   - terraform init -backend-config="token=${TF_API_TOKEN}"
   cache:
    directories:
    - ${TRAVIS_BUILD_DIR}
 - stage: terraform plan
   <<: *terraform_init
   script:
   - terraform plan
 - stage: terraform apply
   <<: *terraform_init
   script:
   - terraform apply -auto-approve
 - stage: terraform destroy
   script:
   - terraform destroy -auto-approve
