#Define Linux Environment
dist: xenial
language: bash

branches:
  only:
    -master
before_installation:
  - wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
  - unzip terraform_0.12.24_linux_amd64.zip
  - sudo mv ./terraform ~/bin
  - terraform --version
jobs:
  include:
    - stage: terraform init
      if: type IN (push) and branch = master
      script:
        - terraform init -force-copy
    - stage: terraform plan
      if: type IN (push) and branch = master
      script:
        - terraform plan
    - stage: terraform apply
      if: type IN (push) and branch = master
      script:
        - terraform apply -auto-approve
     - stage: terraform destroy
      if: type IN (push) and branch = master
      script:
        - terraform destroy -auto-approve
