#Define Linux Environment
dist: bionic
language: bash

branches:
 only:
 - master
before_install:
 - wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
 - unzip terraform_0.12.24_linux_amd64.zip
 - sudo mv ./terraform ~/bin
 - terraform --version
jobs:
 include:
 - stage: terraform init -backend-config="token=${TF_API_TOKEN}"
   script:
   - terraform init -force-copy
 - stage: terraform plan
   script:
   - terraform plan
 - stage: terraform apply
   script:
   - terraform apply -auto-approve
 - stage: terraform destroy
   script:
   - terraform destroy -auto-approve
